name: Build and Push Docker Images for Blog Application

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Blog Service Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-service:latest ./blog-service
        docker push ${{ secrets.DOCKER_USERNAME }}/blog-service:latest

    - name: Build and Push Comment Service Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/comment-service:latest ./comment-service
        docker push ${{ secrets.DOCKER_USERNAME }}/comment-service:latest

    - name: Build and Push User Service Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./user-service
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

    - name: Build and Push Gateway Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/gateway:latest ./gateway
        docker push ${{ secrets.DOCKER_USERNAME }}/gateway:latest
